//! Message types for brain input and output.

/// An incoming message to be processed by the brain.
#[derive(Debug, Clone)]
pub struct InboundMessage {
    /// The sender's identifier (phone number in E.164 format).
    pub sender: String,

    /// The message text content.
    pub text: String,

    /// Unix timestamp in milliseconds when the message was sent.
    pub timestamp: u64,

    /// Group ID if this is a group message, None for direct messages.
    pub group_id: Option<String>,
}

/// An outgoing message generated by the brain.
#[derive(Debug, Clone)]
pub struct OutboundMessage {
    /// The recipient's identifier (phone number or group ID).
    pub recipient: String,

    /// The response text content.
    pub text: String,

    /// Whether this is a group message.
    pub is_group: bool,
}

impl InboundMessage {
    /// Create a new direct message.
    pub fn direct(sender: impl Into<String>, text: impl Into<String>, timestamp: u64) -> Self {
        Self {
            sender: sender.into(),
            text: text.into(),
            timestamp,
            group_id: None,
        }
    }

    /// Create a new group message.
    pub fn group(
        sender: impl Into<String>,
        text: impl Into<String>,
        timestamp: u64,
        group_id: impl Into<String>,
    ) -> Self {
        Self {
            sender: sender.into(),
            text: text.into(),
            timestamp,
            group_id: Some(group_id.into()),
        }
    }
}

impl OutboundMessage {
    /// Create a reply to an inbound message.
    pub fn reply_to(inbound: &InboundMessage, text: impl Into<String>) -> Self {
        if let Some(group_id) = &inbound.group_id {
            Self {
                recipient: group_id.clone(),
                text: text.into(),
                is_group: true,
            }
        } else {
            Self {
                recipient: inbound.sender.clone(),
                text: text.into(),
                is_group: false,
            }
        }
    }

    /// Create a direct message to a recipient.
    pub fn direct(recipient: impl Into<String>, text: impl Into<String>) -> Self {
        Self {
            recipient: recipient.into(),
            text: text.into(),
            is_group: false,
        }
    }
}
